### PR TITLE
Slightly speed up and format

### PR DESCRIPTION
**Pull request by liushuyu**
Using StringIO instead of tempfile, using autopep8 to format

### CODE REVIEW

**Comment by gumblex** [comment]
Have you tested?

**Comment by liushuyu** [comment]
> Have you tested?

Yes, of course. You can test it if you have doubt

**Comment by liushuyu** [comment]
We can even set  up CI to test this automatically -- If you want to

**Comment by gumblex** [comment]
```
2016-10-09 14:00:44,309 W ../aosc-os-abbs/extra-vcs/cvs/autobuild/defines: /bin/sh: 29: export: LIBS+: bad variable name
Traceback (most recent call last):
  File "abbsmeta.py", line 131, in <module>
    sys.exit(main(*sys.argv[1:]))
  File "abbsmeta.py", line 126, in main
    scan_abbs_tree(cur, path)
  File "abbsmeta.py", line 97, in scan_abbs_tree
    os.path.join(dirpath, 'defines')))
  File "abbsmeta.py", line 74, in read_bash_vars
    assert len(var) == len(lines)
AssertionError
```

**Comment by liushuyu** [comment]
I haven't encounter anything... Can you insert `print(tmpf.getvalue())` after L68 and before L69?

**Pull request merged**
